/** Static tooltip descriptions for FFG narrative dice symbols */

export interface SymbolTooltip {
  name:        string
  icon:        string
  color:       string
  description: string
  spendOn:     string[]
}

export const SYMBOL_TIPS: Record<string, SymbolTooltip> = {
  S: {
    name:        'Success',
    icon:        '⬟',
    color:       '#4EC87A',
    description: 'Successes determine whether a task is accomplished. A roll needs at least 1 net Success to succeed. Extra Successes increase the degree of accomplishment.',
    spendOn:     [
      'The task succeeds',
      'Extra Successes increase damage dealt (1 Success = +1 damage)',
      'Meet the threshold for harder activities (e.g., 3 Successes to jury-rig)',
    ],
  },
  F: {
    name:        'Failure',
    icon:        '⬟',
    color:       '#E05050',
    description: 'Failures cancel Successes one-for-one. If Failures outnumber Successes, the check fails. The GM decides the narrative consequences.',
    spendOn:     [
      'Cancels Successes (net result determines pass/fail)',
      'Net Failures can make failure more catastrophic at GM discretion',
    ],
  },
  A: {
    name:        'Advantage',
    icon:        '◈',
    color:       '#5AAAE0',
    description: 'Advantage represents positive side-effects and opportunities, even on failed rolls. Spend it to gain extra effects beyond success or failure.',
    spendOn:     [
      '2 Advantage: Recover 1 Strain',
      '2 Advantage: Activate a weapon quality',
      '3 Advantage: Additional hit (Auto-fire)',
      '1 Advantage: Add a Boost die to next allied check',
      '1 Advantage: Notice something useful in the environment',
    ],
  },
  H: {
    name:        'Threat',
    icon:        '◈',
    color:       '#B070D8',
    description: 'Threat cancels Advantage and generates negative side-effects. The GM (or the table) spends Threat against the active character, even on successful rolls.',
    spendOn:     [
      '2 Threat: Suffer 1 Strain',
      '2 Threat: Lose the benefits of cover or concealment',
      '3 Threat: A weapon quality activates against you',
      '1 Threat: Add a Setback die to next allied check',
    ],
  },
  T: {
    name:        'Triumph',
    icon:        '✦',
    color:       '#C8AA50',
    description: 'Triumph counts as 1 Success AND provides a powerful additional effect. It represents moments of extraordinary fortune — a signature move landing perfectly.',
    spendOn:     [
      'Counts as 1 Success (stackable)',
      'Activate a weapon\'s Critical Injury effect',
      'Gain an extra free action this turn',
      'Perform an action that normally costs additional resources',
      'Find an extraordinarily useful item or information',
    ],
  },
  D: {
    name:        'Despair',
    icon:        '✦',
    color:       '#E05050',
    description: 'Despair counts as 1 Failure AND generates a catastrophic side-effect chosen by the GM. It represents terrible luck or a critical mistake at the worst moment.',
    spendOn:     [
      'Counts as 1 Failure',
      'Weapon runs out of ammo or malfunctions',
      'Severe Critical Injury result',
      'An ally suffers an unexpected complication',
      'The situation dramatically worsens for the party',
    ],
  },
  FORCE_LIGHT: {
    name:        'Light Side Force Point',
    icon:        '○',
    color:       '#C8D8C0',
    description: 'Generated by Force dice on a light side result. Can be used to power Force abilities. Spending Light Side points keeps you aligned with the light side of the Force.',
    spendOn:     [
      'Activate Force power upgrades',
      'Generates Conflict if spent as Dark Side by a light-side character',
    ],
  },
  FORCE_DARK: {
    name:        'Dark Side Force Point',
    icon:        '●',
    color:       '#9060D0',
    description: 'Generated by Force dice on a dark side result. Can be converted to Light Side pips at a 2:1 cost, or used directly (generating Conflict for light-side characters).',
    spendOn:     [
      'Activate Force power upgrades (cost: Conflict for light-siders)',
      '2 Dark Side → 1 Light Side pip',
      'Dark-side characters spend these freely',
    ],
  },
}
