-- Weapon quality reference table, seeded from OggDude DataCustom/ItemDescriptors.xml

create table if not exists ref_weapon_qualities (
  key         text primary key,
  name        text not null,
  description text not null default '',
  is_ranked   boolean not null default false
);

alter table ref_weapon_qualities enable row level security;

create policy "anon read ref_weapon_qualities"
  on ref_weapon_qualities for select to anon using (true);

create policy "auth read ref_weapon_qualities"
  on ref_weapon_qualities for select to authenticated using (true);

insert into ref_weapon_qualities (key, name, description, is_ranked) values
  ('ACCURATE',        'Accurate',             'Accurate weapons are easier to aim or wield, whether through design or technology. For each level of this trait, the attacker adds Boost dice to his attack dice pools while using this weapon.',                                                                                                                                                                                 true),
  ('AUTOFIRE',        'Auto-Fire',             'A weapon with Auto-fire can be set to shoot in rapid succession and potentially spray an area. Attacking with Auto-fire increases the difficulty of the attack by one. If the attack hits, spend Advantage to trigger Auto-fire for additional hits. Each additional hit deals base damage plus uncancelled Successes and can target any designated target within range.',    false),
  ('BLAST',           'Blast',                 'The weapon has a large spread or explosive blast. If the attack is successful and Blast activates, each character Engaged with the original target suffers wounds equal to the weapon''s Blast rating. The user may also trigger Blast if the attack misses by spending Advantage — the original target and everyone engaged with them suffers damage equal to the Blast rating.', true),
  ('BREACH',          'Breach',                'Weapons with Breach burn through the toughest armor. Breach weapons ignore one point of Armor for every rating of Breach (and also ignore 10 points of soak per Breach rating).',                                                                                                                                                                                             true),
  ('BURN',            'Burn',                  'Weapons with Burn inflict damage over time. If the attack is successful, the target continues to suffer the weapon''s base damage for a number of rounds equal to the weapon''s Burn rating. Damage is applied at the start of each of the target''s actions. A victim may attempt a Coordination check to extinguish the flames.',                                           true),
  ('CONCUSSIVE',      'Concussive',            'The weapon''s attack can stagger a target from mighty blows or shockwaves. The target is staggered for a number of rounds equal to the weapon''s Concussive rating. A staggered target cannot perform actions.',                                                                                                                                                              true),
  ('CORTOSIS',        'Cortosis',              'Weapons with the Cortosis quality are immune to the Sunder quality. Armor with the Cortosis quality makes the wearer''s soak immune to the Pierce and Breach qualities. Cortosis ore is extremely rare and valuable.',                                                                                                                                                         false),
  ('CUMBERSOME',      'Cumbersome',            'A Cumbersome weapon is large, unwieldy, or heavy. To wield it properly, the character needs a Brawn equal to or greater than the weapon''s Cumbersome rating. For each point of Brawn the character is deficient, they must increase the difficulty of all checks with the weapon by one.',                                                                                   true),
  ('DEFENSIVE',       'Defensive',             'Defensive weapons are particularly good at fending off incoming melee attacks. A character wielding a weapon with the Defensive quality increases their melee defense by the weapon''s Defensive rating.',                                                                                                                                                                    true),
  ('DEFLECTION',      'Deflection',            'An item with the Deflection quality increases the wearer''s ranged defense equal to its Deflection rating.',                                                                                                                                                                                                                                                                 true),
  ('DISORIENT',       'Disorient',             'A weapon with Disorient can daze an opponent. When Disorient is triggered, the target is disoriented for a number of rounds equal to the weapon''s Disorient rating. A disoriented target adds Setback dice to all skill checks.',                                                                                                                                           true),
  ('ENSNARE',         'Ensnare',               'A weapon with Ensnare binds a foe and restricts their movements. When Ensnare is triggered, the target is immobilized for a number of rounds equal to the weapon''s Ensnare rating. An Ensnared target may attempt a Hard Athletics check as an action to break free. An immobilized target cannot perform maneuvers.',                                                     true),
  ('GUIDED',          'Guided',                'If a character misses while firing a Guided weapon and Guided activates, they may make another attack check at the end of the round. The check''s Ability dice equal the weapon''s Guided rating. If successful, the weapon strikes the target and damage is dealt normally.',                                                                                                 true),
  ('INACCURATE',      'Inaccurate',            'Inaccurate weapons are of shoddy or inferior construction. They add Setback dice to the attacker''s dice pool equal to their Inaccurate rating.',                                                                                                                                                                                                                            true),
  ('INFERIOR',        'Inferior',              'An Inferior item represents shoddy craftsmanship. An Inferior weapon generates automatic Threat on all checks related to its use and has its base damage decreased by one. Inferior armor has its encumbrance increased by one and its defense decreased by one.',                                                                                                             false),
  ('ION',             'Ion',                   'Ion weapons are designed to affect electrical systems. They deal damage as system strain (usually on vehicles) rather than wounds. Droids are affected by ion weapons, taking damage to their strain threshold.',                                                                                                                                                              false),
  ('KNOCKDOWN',       'Knockdown',             'When Knockdown triggers, the target is knocked prone. Unless specified otherwise, Knockdown requires Advantage to trigger, plus one additional Advantage per silhouette beyond one.',                                                                                                                                                                                         false),
  ('LIMITEDAMMO',     'Limited Ammo',          'A weapon with the Limited Ammo quality may be used to make a number of attacks equal to its Limited Ammo rating before it must be reloaded with a maneuver. Each shot expends one of a limited number of rounds of ammo that must be obtained before the weapon can be used again.',                                                                                         true),
  ('LINKED',          'Linked',                'Linked weapons are designed to fire together at the same target. On a successful attack, spend Advantage to gain additional hits, up to the weapon''s Linked rating. Additional hits may only be applied against the original target. Each hit deals the weapon''s base damage plus total Successes.',                                                                        true),
  ('PIERCE',          'Pierce',                'An attack made with this weapon ignores one point of soak for each rank of Pierce. If the weapon has more ranks of Pierce than the target''s total soak, it completely ignores the target''s soak.',                                                                                                                                                                         true),
  ('PREPARE',         'Prepare',               'Weapons with this quality require time to set up before being used. The user must perform a number of preparation maneuvers equal to the weapon''s Prepare rating before making attacks.',                                                                                                                                                                                   true),
  ('SLOWFIRING',      'Slow-Firing',           'Slow-Firing weapons need time to recharge or cool down between shots. A weapon''s Slow-Firing rating dictates how many rounds must pass after firing before it can be fired again.',                                                                                                                                                                                         true),
  ('STAGGER',         'Stagger',               '',                                                                                                                                                                                                                                                                                                                                                                          true),
  ('STUN',            'Stun',                  'A weapon with Stun causes strain to the target. When the Stun quality is activated, it inflicts strain equal to the weapon''s Stun rating.',                                                                                                                                                                                                                                 true),
  ('STUNDAMAGE',      'Stun Damage',           'This weapon deals Stun damage instead of regular damage — it deals damage as strain instead of wounds. This damage is still reduced by the target''s soak.',                                                                                                                                                                                                                 false),
  ('STUNDAMAGEDROID', 'Stun Damage (Droid)',   'This weapon deals Stun damage to droids instead of regular damage — it deals damage as strain instead of wounds. This damage is still reduced by the target''s soak.',                                                                                                                                                                                                      false),
  ('STUNDROID',       'Stun (Droid Only)',     'A weapon with Stun (Droid Only) causes strain to droid targets. When activated, it inflicts strain equal to the weapon''s Stun rating against droids.',                                                                                                                                                                                                                     true),
  ('STUNSETTING',     'Stun Setting',          'As a free action, the wielder can switch the weapon to Stun mode. In Stun mode, it deals damage as strain instead of wounds, still reduced by soak. When using the stun setting, the weapon''s range changes to Short and cannot be increased.',                                                                                                                             false),
  ('SUNDER',          'Sunder',                'When activated, the attacker chooses one item openly wielded by the target. That item is damaged one step (from undamaged to Minor, Minor to Moderate, or Moderate to Major). A weapon at Major damage that is Sundered is destroyed. Sunder requires Advantage to activate.',                                                                                               false),
  ('SUPERIOR',        'Superior',              'A Superior item represents masterful craftsmanship. A Superior weapon generates automatic Advantage on all attacks and has its base damage increased by one. Superior armor has its encumbrance reduced by one and its soak value increased by one.',                                                                                                                          false),
  ('TRACTOR',         'Tractor',               'This weapon fires electromagnetic beams that ensnare ships and hold them fast. Once the weapon hits its target, the target may not move unless its pilot makes a successful Piloting check with difficulty based on the tractor beam''s rating.',                                                                                                                             true),
  ('UNWIELDY',        'Unwieldy',              'An Unwieldy weapon is awkward to use without impressive dexterity. To wield it properly, the character needs an Agility equal to or greater than the weapon''s Unwieldy rating. For each point of Agility by which the character is deficient, they must increase the difficulty of all checks with the weapon by one.',                                                     true),
  ('VICIOUS',         'Vicious',               'When this weapon scores a critical injury or hit, the character adds ten times the Vicious rating to the critical roll. With Vicious 3, for example, the victim adds +30 to their critical hit result.',                                                                                                                                                                     true),
  ('VICIOUSDROID',    'Vicious (Droid Only)',  'When this weapon scores a critical injury or hit against a droid, the character adds ten times the Vicious rating to the critical roll.',                                                                                                                                                                                                                                    true)
on conflict (key) do update set
  name        = excluded.name,
  description = excluded.description,
  is_ranked   = excluded.is_ranked;
