-- =============================================================================
-- Migration 058: Seed species skill_rank abilities and talent career_skills
--
-- Part A: For every species that has OggDude SkillModifiers, append a
--   skill_rank entry to ref_species.special_abilities (idempotent --
--   uses NOT EXISTS so re-running is safe).  These entries are read by the
--   hudSkills overlay in useCharacterData to add the species starting rank
--   on top of the player purchased rank stored in character_skills.
--
-- Part B: For every talent whose OggDude XML contains a ChooseCareerSkills
--   element with fixed (non-player-choice) skill keys, merge a career_skills
--   array into ref_talents.modifiers.  This is consumed by hudSkills to
--   set isCareer = true for those skills whenever the talent is purchased.
--   WELLREAD and WELLROUND are intentionally excluded -- they require a
--   player choice and need separate UX work.
-- =============================================================================

-- ── Part A: Species skill_rank special_abilities ──────────────────────────
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ALEENA_SKILL_COORD", "name": "Starting Skill: Coordination", "description": "Gain 1 rank in Coordination (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["COORD"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'ALEENA' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ALEENA_SKILL_COORD');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "AQUA_SKILL_BRAWL", "name": "Starting Skill: Brawl", "description": "Gain 1 rank in Brawl (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["BRAWL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'AQUA' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'AQUA_SKILL_BRAWL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ARCONA_SKILL_VIGIL", "name": "Starting Skill: Vigilance", "description": "Gain 1 rank in Vigilance (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["VIGIL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'ARCONA' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ARCONA_SKILL_VIGIL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ARKAN_SKILL_MED", "name": "Starting Skill: Medicine", "description": "Gain 1 rank in Medicine (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["MED"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'ARKAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ARKAN_SKILL_MED');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "BALOSAR_SKILL_SW", "name": "Starting Skill: Streetwise", "description": "Gain 1 rank in Streetwise (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["SW"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'BALOSAR' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'BALOSAR_SKILL_SW');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "BARAB_SKILL_COERC", "name": "Starting Skill: Coercion", "description": "Gain 1 rank in Coercion (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["COERC"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'BARAB' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'BARAB_SKILL_COERC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "BARDOTTAN_SKILL_LORE", "name": "Starting Skill: Lore", "description": "Gain 1 rank in Lore (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["LORE"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'BARDOTTAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'BARDOTTAN_SKILL_LORE');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "BESALISK_SKILL_RESIL", "name": "Starting Skill: Resilience", "description": "Gain 1 rank in Resilience (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["RESIL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'BESALISK' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'BESALISK_SKILL_RESIL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "BITH_SKILL_PERC", "name": "Starting Skill: Perception", "description": "Gain 1 rank in Perception (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["PERC"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'BITH' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'BITH_SKILL_PERC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "BOTH_SKILL_SW", "name": "Starting Skill: Streetwise", "description": "Gain 1 rank in Streetwise (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["SW"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'BOTH' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'BOTH_SKILL_SW');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "CEREAN_SKILL_VIGIL", "name": "Starting Skill: Vigilance", "description": "Gain 1 rank in Vigilance (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["VIGIL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'CEREAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'CEREAN_SKILL_VIGIL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "CHADRA_SKILL_MECH", "name": "Starting Skill: Mechanics", "description": "Gain 1 rank in Mechanics (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["MECH"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'CHADRA' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'CHADRA_SKILL_MECH');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "CHAGRIAN_SKILL_RESIL", "name": "Starting Skill: Resilience", "description": "Gain 1 rank in Resilience (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["RESIL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'CHAGRIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'CHAGRIAN_SKILL_RESIL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "CHEVIN_SKILL_NEG", "name": "Starting Skill: Negotiation", "description": "Gain 1 rank in Negotiation.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["NEG"], "rank_start": 1}]'::jsonb WHERE key = 'CHEVIN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'CHEVIN_SKILL_NEG');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "CHISS_SKILL_COOL", "name": "Starting Skill: Cool", "description": "Gain 1 rank in Cool (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["COOL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'CHISS' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'CHISS_SKILL_COOL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "CLAWDITE_SKILL_RESIL", "name": "Starting Skill: Resilience", "description": "Gain 1 rank in Resilience.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["RESIL"], "rank_start": 1}]'::jsonb WHERE key = 'CLAWDITE' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'CLAWDITE_SKILL_RESIL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "CLONE_SKILL_WARF", "name": "Starting Skill: Warfare", "description": "Gain 1 rank in Warfare (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["WARF"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'CLONE' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'CLONE_SKILL_WARF');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "CLONE_SKILL_RESIL", "name": "Starting Skill: Resilience", "description": "Gain 1 rank in Resilience (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["RESIL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'CLONE' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'CLONE_SKILL_RESIL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "COSIAN_SKILL_LORE", "name": "Starting Skill: Lore", "description": "Gain 1 rank in Lore (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["LORE"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'COSIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'COSIAN_SKILL_LORE');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "DATHOMIRIAN_SKILL_COERC", "name": "Starting Skill: Coercion", "description": "Gain 1 rank in Coercion.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["COERC"], "rank_start": 1}]'::jsonb WHERE key = 'DATHOMIRIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'DATHOMIRIAN_SKILL_COERC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "DATHOMIRIAN_SKILL_SURV", "name": "Starting Skill: Survival", "description": "Gain 1 rank in Survival.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["SURV"], "rank_start": 1}]'::jsonb WHERE key = 'DATHOMIRIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'DATHOMIRIAN_SKILL_SURV');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "DEFEL_SKILL_VIGIL", "name": "Starting Skill: Vigilance", "description": "Gain 1 rank in Vigilance (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["VIGIL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'DEFEL' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'DEFEL_SKILL_VIGIL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "DOWUTIN_SKILL_RESIL", "name": "Starting Skill: Resilience", "description": "Gain 1 rank in Resilience (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["RESIL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'DOWUTIN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'DOWUTIN_SKILL_RESIL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "DRALL_SKILL_EDU", "name": "Starting Skill: Education", "description": "Gain 1 rank in Education (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["EDU"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'DRALL' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'DRALL_SKILL_EDU');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "DRESSELLIAN_SKILL_SURV", "name": "Starting Skill: Survival", "description": "Gain 1 rank in Survival (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["SURV"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'DRESSELLIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'DRESSELLIAN_SKILL_SURV');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "DUG_SKILL_BRAWL", "name": "Starting Skill: Brawl", "description": "Gain 1 rank in Brawl (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["BRAWL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'DUG' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'DUG_SKILL_BRAWL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "DUROS_SKILL_PILOTSP", "name": "Starting Skill: Piloting - Space", "description": "Gain 1 rank in Piloting - Space.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["PILOTSP"], "rank_start": 1}]'::jsonb WHERE key = 'DUROS' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'DUROS_SKILL_PILOTSP');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ELOM_SKILL_RESIL", "name": "Starting Skill: Resilience", "description": "Gain 1 rank in Resilience.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["RESIL"], "rank_start": 1}]'::jsonb WHERE key = 'ELOM' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ELOM_SKILL_RESIL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ELOMIN_SKILL_CHARM", "name": "Starting Skill: Charm", "description": "Gain 1 rank in Charm.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["CHARM"], "rank_start": 1}]'::jsonb WHERE key = 'ELOMIN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ELOMIN_SKILL_CHARM');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ELOMIN_SKILL_EDU", "name": "Starting Skill: Education", "description": "Gain 1 rank in Education.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["EDU"], "rank_start": 1}]'::jsonb WHERE key = 'ELOMIN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ELOMIN_SKILL_EDU');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "FALLEEN_SKILL_CHARM", "name": "Starting Skill: Charm", "description": "Gain 1 rank in Charm (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["CHARM"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'FALLEEN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'FALLEEN_SKILL_CHARM');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "GAMORREAN_SKILL_MELEE", "name": "Starting Skill: Melee", "description": "Gain 1 rank in Melee (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["MELEE"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'GAMORREAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'GAMORREAN_SKILL_MELEE');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "GAND_SKILL_DISC", "name": "Starting Skill: Discipline", "description": "Gain 1 rank in Discipline (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["DISC"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'GAND' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'GAND_SKILL_DISC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "GIGORAN_SKILL_BRAWL", "name": "Starting Skill: Brawl", "description": "Gain 1 rank in Brawl.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["BRAWL"], "rank_start": 1}]'::jsonb WHERE key = 'GIGORAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'GIGORAN_SKILL_BRAWL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "GIVIN_SKILL_EDU", "name": "Starting Skill: Education", "description": "Gain 1 rank in Education (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["EDU"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'GIVIN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'GIVIN_SKILL_EDU');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "GOSSAM_SKILL_DECEP", "name": "Starting Skill: Deception", "description": "Gain 1 rank in Deception (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["DECEP"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'GOSSAM' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'GOSSAM_SKILL_DECEP');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "GOTAL_SKILL_PERC", "name": "Starting Skill: Perception", "description": "Gain 1 rank in Perception (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["PERC"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'GOTAL' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'GOTAL_SKILL_PERC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "GUNGAN_SKILL_ATHL", "name": "Starting Skill: Athletics", "description": "Gain 1 rank in Athletics (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["ATHL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'GUNGAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'GUNGAN_SKILL_ATHL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "HERGLIC_SKILL_CHARM", "name": "Starting Skill: Charm", "description": "Gain 1 rank in Charm.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["CHARM"], "rank_start": 1}]'::jsonb WHERE key = 'HERGLIC' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'HERGLIC_SKILL_CHARM');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "IAKARU_SKILL_PILOTSP", "name": "Starting Skill: Piloting - Space", "description": "Gain 1 rank in Piloting - Space.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["PILOTSP"], "rank_start": 1}]'::jsonb WHERE key = 'IAKARU' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'IAKARU_SKILL_PILOTSP');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "IKTOTCHI_SKILL_VIGIL", "name": "Starting Skill: Vigilance", "description": "Gain 1 rank in Vigilance.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["VIGIL"], "rank_start": 1}]'::jsonb WHERE key = 'IKTOTCHI' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'IKTOTCHI_SKILL_VIGIL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ISHITIB_SKILL_DISC", "name": "Starting Skill: Discipline", "description": "Gain 1 rank in Discipline (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["DISC"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'ISHITIB' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ISHITIB_SKILL_DISC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ITHORIAN_SKILL_SURV", "name": "Starting Skill: Survival", "description": "Gain 1 rank in Survival.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["SURV"], "rank_start": 1}]'::jsonb WHERE key = 'ITHORIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ITHORIAN_SKILL_SURV');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "JAWA_SKILL_MECH", "name": "Starting Skill: Mechanics", "description": "Gain 1 rank in Mechanics.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["MECH"], "rank_start": 1}]'::jsonb WHERE key = 'JAWA' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'JAWA_SKILL_MECH');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "KALLERAN_SKILL_SW", "name": "Starting Skill: Streetwise", "description": "Gain 1 rank in Streetwise.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["SW"], "rank_start": 1}]'::jsonb WHERE key = 'KALLERAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'KALLERAN_SKILL_SW');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "KAMINOAN_SKILL_MED", "name": "Starting Skill: Medicine", "description": "Gain 1 rank in Medicine (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["MED"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'KAMINOAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'KAMINOAN_SKILL_MED');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "KELDOR_SKILL_EDU", "name": "Starting Skill: Education", "description": "Gain 1 rank in Education (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["EDU"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'KELDOR' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'KELDOR_SKILL_EDU');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "KYUZO_SKILL_COORD", "name": "Starting Skill: Coordination", "description": "Gain 1 rank in Coordination.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["COORD"], "rank_start": 1}]'::jsonb WHERE key = 'KYUZO' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'KYUZO_SKILL_COORD');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "LANNIK_SKILL_SW", "name": "Starting Skill: Streetwise", "description": "Gain 1 rank in Streetwise.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["SW"], "rank_start": 1}]'::jsonb WHERE key = 'LANNIK' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'LANNIK_SKILL_SW');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "MELITTO_SKILL_PERC", "name": "Starting Skill: Perception", "description": "Gain 1 rank in Perception (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["PERC"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'MELITTO' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'MELITTO_SKILL_PERC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "MIKKIAN_SKILL_DISC", "name": "Starting Skill: Discipline", "description": "Gain 1 rank in Discipline (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["DISC"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'MIKKIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'MIKKIAN_SKILL_DISC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "MIRIALAN_SKILL_DISC", "name": "Starting Skill: Discipline", "description": "Gain 1 rank in Discipline (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["DISC"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'MIRIALAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'MIRIALAN_SKILL_DISC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "MIRIALAN_SKILL_COOL", "name": "Starting Skill: Cool", "description": "Gain 1 rank in Cool (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["COOL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'MIRIALAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'MIRIALAN_SKILL_COOL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "MONCAL_SKILL_EDU", "name": "Starting Skill: Education", "description": "Gain 1 rank in Education.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["EDU"], "rank_start": 1}]'::jsonb WHERE key = 'MONCAL' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'MONCAL_SKILL_EDU');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "MUSTAFARIAN_SKILL_BRAWL", "name": "Starting Skill: Brawl", "description": "Gain 1 rank in Brawl (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["BRAWL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'MUSTAFARIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'MUSTAFARIAN_SKILL_BRAWL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "MUUN_SKILL_EDU", "name": "Starting Skill: Education", "description": "Gain 1 rank in Education (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["EDU"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'MUUN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'MUUN_SKILL_EDU');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "MUUN_SKILL_CORE", "name": "Starting Skill: Core Worlds", "description": "Gain 1 rank in Core Worlds (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["CORE"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'MUUN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'MUUN_SKILL_CORE');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "NAUTOLAN_SKILL_ATHL", "name": "Starting Skill: Athletics", "description": "Gain 1 rank in Athletics.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["ATHL"], "rank_start": 1}]'::jsonb WHERE key = 'NAUTOLAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'NAUTOLAN_SKILL_ATHL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "NOGHRI_SKILL_BRAWL", "name": "Starting Skill: Brawl", "description": "Gain 1 rank in Brawl.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["BRAWL"], "rank_start": 1}]'::jsonb WHERE key = 'NOGHRI' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'NOGHRI_SKILL_BRAWL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ORTOLAN_SKILL_SURV", "name": "Starting Skill: Survival", "description": "Gain 1 rank in Survival.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["SURV"], "rank_start": 1}]'::jsonb WHERE key = 'ORTOLAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ORTOLAN_SKILL_SURV');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "POLISMASSAN_SKILL_MED", "name": "Starting Skill: Medicine", "description": "Gain 1 rank in Medicine (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["MED"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'POLISMASSAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'POLISMASSAN_SKILL_MED');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "QUARREN_SKILL_NEG", "name": "Starting Skill: Negotiation", "description": "Gain 1 rank in Negotiation (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["NEG"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'QUARREN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'QUARREN_SKILL_NEG');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "QUERMIAN_SKILL_PERC", "name": "Starting Skill: Perception", "description": "Gain 1 rank in Perception (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["PERC"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'QUERMIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'QUERMIAN_SKILL_PERC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ROD_SKILL_SURV", "name": "Starting Skill: Survival", "description": "Gain 1 rank in Survival (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["SURV"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'ROD' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ROD_SKILL_SURV');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "SATHARI_SKILL_COORD", "name": "Starting Skill: Coordination", "description": "Gain 1 rank in Coordination (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["COORD"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'SATHARI' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'SATHARI_SKILL_COORD');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "SELONIAN_SKILL_COORD", "name": "Starting Skill: Coordination", "description": "Gain 1 rank in Coordination (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["COORD"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'SELONIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'SELONIAN_SKILL_COORD');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "SKAKOAN_SKILL_EDU", "name": "Starting Skill: Education", "description": "Gain 1 rank in Education (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["EDU"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'SKAKOAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'SKAKOAN_SKILL_EDU');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "SKAKOAN_SKILL_MECH", "name": "Starting Skill: Mechanics", "description": "Gain 1 rank in Mechanics (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["MECH"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'SKAKOAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'SKAKOAN_SKILL_MECH');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "SLUISSI_SKILL_MECH", "name": "Starting Skill: Mechanics", "description": "Gain 1 rank in Mechanics.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["MECH"], "rank_start": 1}]'::jsonb WHERE key = 'SLUISSI' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'SLUISSI_SKILL_MECH');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "SQUIB_SKILL_NEG", "name": "Starting Skill: Negotiation", "description": "Gain 1 rank in Negotiation.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["NEG"], "rank_start": 1}]'::jsonb WHERE key = 'SQUIB' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'SQUIB_SKILL_NEG');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "SULLUSTAN_SKILL_ASTRO", "name": "Starting Skill: Astrogation", "description": "Gain 1 rank in Astrogation.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["ASTRO"], "rank_start": 1}]'::jsonb WHERE key = 'SULLUSTAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'SULLUSTAN_SKILL_ASTRO');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "TALZ_SKILL_PERC", "name": "Starting Skill: Perception", "description": "Gain 1 rank in Perception (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["PERC"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'TALZ' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'TALZ_SKILL_PERC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "THISSPIASIAN_SKILL_DISC", "name": "Starting Skill: Discipline", "description": "Gain 1 rank in Discipline (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["DISC"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'THISSPIASIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'THISSPIASIAN_SKILL_DISC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "THOLOTHIAN_SKILL_XEN", "name": "Starting Skill: Xenology", "description": "Gain 1 rank in Xenology (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["XEN"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'THOLOTHIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'THOLOTHIAN_SKILL_XEN');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "TOGNATHS_SKILL_COORD", "name": "Starting Skill: Coordination", "description": "Gain 1 rank in Coordination.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["COORD"], "rank_start": 1}]'::jsonb WHERE key = 'TOGNATHS' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'TOGNATHS_SKILL_COORD');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "TOGNATHS_SKILL_PERC", "name": "Starting Skill: Perception", "description": "Gain 1 rank in Perception.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["PERC"], "rank_start": 1}]'::jsonb WHERE key = 'TOGNATHS' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'TOGNATHS_SKILL_PERC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "TOGORIAN_SKILL_COERC", "name": "Starting Skill: Coercion", "description": "Gain 1 rank in Coercion.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["COERC"], "rank_start": 1}]'::jsonb WHERE key = 'TOGORIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'TOGORIAN_SKILL_COERC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "TOGRUTA_SKILL_PERC", "name": "Starting Skill: Perception", "description": "Gain 1 rank in Perception.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["PERC"], "rank_start": 1}]'::jsonb WHERE key = 'TOGRUTA' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'TOGRUTA_SKILL_PERC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "TRAND_SKILL_PERC", "name": "Starting Skill: Perception", "description": "Gain 1 rank in Perception (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["PERC"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'TRAND' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'TRAND_SKILL_PERC');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "UMBARAN_SKILL_DECEP", "name": "Starting Skill: Deception", "description": "Gain 1 rank in Deception (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["DECEP"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'UMBARAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'UMBARAN_SKILL_DECEP');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "VERPINE_SKILL_MECH", "name": "Starting Skill: Mechanics", "description": "Gain 1 rank in Mechanics.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["MECH"], "rank_start": 1}]'::jsonb WHERE key = 'VERPINE' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'VERPINE_SKILL_MECH');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "VURK_SKILL_NEG", "name": "Starting Skill: Negotiation", "description": "Gain 1 rank in Negotiation (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["NEG"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'VURK' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'VURK_SKILL_NEG');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "WHIPHID_SKILL_SURV", "name": "Starting Skill: Survival", "description": "Gain 1 rank in Survival (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["SURV"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'WHIPHID' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'WHIPHID_SKILL_SURV');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "WOOK_SKILL_BRAWL", "name": "Starting Skill: Brawl", "description": "Gain 1 rank in Brawl (max 2).", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["BRAWL"], "rank_start": 1, "rank_limit": 2}]'::jsonb WHERE key = 'WOOK' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'WOOK_SKILL_BRAWL');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ZABRAK_SKILL_SURV", "name": "Starting Skill: Survival", "description": "Gain 1 rank in Survival.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["SURV"], "rank_start": 1}]'::jsonb WHERE key = 'ZABRAK' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ZABRAK_SKILL_SURV');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ZELTRON_SKILL_CHARM", "name": "Starting Skill: Charm", "description": "Gain 1 rank in Charm.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["CHARM"], "rank_start": 1}]'::jsonb WHERE key = 'ZELTRON' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ZELTRON_SKILL_CHARM');
UPDATE ref_species SET special_abilities = COALESCE(special_abilities, '[]'::jsonb) || '[{"key": "ZYGERRIAN_SKILL_COERC", "name": "Starting Skill: Coercion", "description": "Gain 1 rank in Coercion.", "mechanical_type": "skill_rank", "is_conditional": false, "affected_skills": ["COERC"], "rank_start": 1}]'::jsonb WHERE key = 'ZYGERRIAN' AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(COALESCE(special_abilities, '[]'::jsonb)) elem WHERE elem->>'key' = 'ZYGERRIAN_SKILL_COERC');

-- ── Part B: Talent career_skills grants ──────────────────────────────────

-- Basic Combat Training
UPDATE ref_talents SET modifiers = COALESCE(modifiers, '{}'::jsonb) || jsonb_build_object('career_skills', '["BRAWL","RANGLT"]'::jsonb) WHERE key = 'BASICTRAIN';

-- Secrets of the Jedi (Improved)
UPDATE ref_talents SET modifiers = COALESCE(modifiers, '{}'::jsonb) || jsonb_build_object('career_skills', '["DISC"]'::jsonb) WHERE key = 'IMPSECRETJEDI';

-- Insight
UPDATE ref_talents SET modifiers = COALESCE(modifiers, '{}'::jsonb) || jsonb_build_object('career_skills', '["DISC","PERC"]'::jsonb) WHERE key = 'INSIGHT';

-- Pilot Training
UPDATE ref_talents SET modifiers = COALESCE(modifiers, '{}'::jsonb) || jsonb_build_object('career_skills', '["PILOTPL","PILOTSP"]'::jsonb) WHERE key = 'PILOTTRAIN';

-- Secrets of the Force
UPDATE ref_talents SET modifiers = COALESCE(modifiers, '{}'::jsonb) || jsonb_build_object('career_skills', '["LORE","LTSABER"]'::jsonb) WHERE key = 'SECRETFORCE';

-- Secrets of the Jedi
UPDATE ref_talents SET modifiers = COALESCE(modifiers, '{}'::jsonb) || jsonb_build_object('career_skills', '["LTSABER"]'::jsonb) WHERE key = 'SECRETJEDI';

-- Tactical Combat Training
UPDATE ref_talents SET modifiers = COALESCE(modifiers, '{}'::jsonb) || jsonb_build_object('career_skills', '["MELEE","RANGHVY"]'::jsonb) WHERE key = 'TACTTRAIN';

-- Vehicle Combat Training
UPDATE ref_talents SET modifiers = COALESCE(modifiers, '{}'::jsonb) || jsonb_build_object('career_skills', '["GUNN","PILOTPL"]'::jsonb) WHERE key = 'VEHTRAIN';

-- Well Traveled
UPDATE ref_talents SET modifiers = COALESCE(modifiers, '{}'::jsonb) || jsonb_build_object('career_skills', '["CORE","OUT"]'::jsonb) WHERE key = 'WELLTRAV';
